spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    add-properties: false
  freemarker:
    cache: false
  jwt:
    secret: runwithme
  datasource:
    url: jdbc:mysql://localhost:3306/third?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      fail-on-empty-beans: false

cloud:
  aws:
    s3:
      bucket: soonirwm
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAVG2YBEGADFRCUNHQ
      secretKey: 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
      
      