spring:
  datasource:
    url: jdbc:mysql://localhost:3306/third?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true